/* Generated by re2c 0.16 */
// Copyright 2011 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "lexer.h"

#include <stdio.h>

#include "eval_env.h"
#include "util.h"

bool Lexer::Error(const string& message, string* err) {
  // Compute line/column.
  int line = 1;
  const char* context = input_.str_;
  for (const char* p = input_.str_; p < last_token_; ++p) {
    if (*p == '\n') {
      ++line;
      context = p + 1;
    }
  }
  int col = last_token_ ? (int)(last_token_ - context) : 0;

  char buf[1024];
  snprintf(buf, sizeof(buf), "%s:%d: ", filename_.AsString().c_str(), line);
  *err = buf;
  *err += message + "\n";

  // Add some context to the message.
  const int kTruncateColumn = 72;
  if (col > 0 && col < kTruncateColumn) {
    int len;
    bool truncated = true;
    for (len = 0; len < kTruncateColumn; ++len) {
      if (context[len] == 0 || context[len] == '\n') {
        truncated = false;
        break;
      }
    }
    *err += string(context, len);
    if (truncated)
      *err += "...";
    *err += "\n";
    *err += string(col, ' ');
    *err += "^ near here";
  }

  return false;
}

Lexer::Lexer(const char* input) {
  Start("input", input);
}

void Lexer::Start(StringPiece filename, StringPiece input) {
  filename_ = filename;
  input_ = input;
  ofs_ = input_.str_;
  last_token_ = NULL;
}

const char* Lexer::TokenName(Token t) {
  switch (t) {
  case ERROR:    return "lexing error";
  case BUILD:    return "'build'";
  case COLON:    return "':'";
  case DEFAULT:  return "'default'";
  case EQUALS:   return "'='";
  case PLUSEQ:   return "'+='";
  case IDENT:    return "identifier";
  case INCLUDE:  return "'include'";
  case INDENT:   return "indent";
  case NEWLINE:  return "newline";
  case PIPE2:    return "'||'";
  case PIPE:     return "'|'";
  case POOL:     return "'pool'";
  case RULE:     return "'rule'";
  case SUBNINJA: return "'subninja'";
  case FOR:      return "'for'";
  case IN_:      return "'in'";
  case END:      return "'end'";
  case TEOF:     return "eof";
  }
  return NULL;  // not reached
}

const char* Lexer::TokenErrorHint(Token expected) {
  switch (expected) {
  case COLON:
    return " ($ also escapes ':')";
  default:
    return "";
  }
}

string Lexer::DescribeLastError() {
  if (last_token_) {
    switch (last_token_[0]) {
    case '\t':
      return "tabs are not allowed, use spaces";
    }
  }
  return "lexing error";
}

void Lexer::UnreadToken() {
  ofs_ = last_token_;
}

Lexer::Token Lexer::ReadToken() {
  const char* p = ofs_;
  const char* q;
  const char* start;
  Lexer::Token token;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		160, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 192, 192, 128, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 128, 128, 128, 128, 128, 128, 
		128, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 128, 128, 128, 128, 192, 
		128, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy9;
	}
	if (yych <= '^') {
		if (yych <= '+') {
			if (yych <= '\f') {
				if (yych <= 0x00) goto yy2;
				if (yych == '\n') goto yy6;
				goto yy4;
			} else {
				if (yych <= '"') {
					if (yych <= '\r') goto yy8;
					goto yy4;
				} else {
					if (yych <= '#') goto yy12;
					if (yych <= '*') goto yy4;
					goto yy13;
				}
			}
		} else {
			if (yych <= ':') {
				if (yych <= '.') {
					if (yych <= ',') goto yy4;
					goto yy14;
				} else {
					if (yych <= '/') goto yy4;
					if (yych <= '9') goto yy14;
					goto yy17;
				}
			} else {
				if (yych <= '=') {
					if (yych <= '<') goto yy4;
					goto yy19;
				} else {
					if (yych <= '@') goto yy4;
					if (yych <= 'Z') goto yy14;
					goto yy4;
				}
			}
		}
	} else {
		if (yych <= 'h') {
			if (yych <= 'b') {
				if (yych == '`') goto yy4;
				if (yych <= 'a') goto yy14;
				goto yy21;
			} else {
				if (yych <= 'd') {
					if (yych <= 'c') goto yy14;
					goto yy22;
				} else {
					if (yych <= 'e') goto yy23;
					if (yych <= 'f') goto yy24;
					goto yy14;
				}
			}
		} else {
			if (yych <= 'r') {
				if (yych <= 'o') {
					if (yych <= 'i') goto yy25;
					goto yy14;
				} else {
					if (yych <= 'p') goto yy26;
					if (yych <= 'q') goto yy14;
					goto yy27;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 's') goto yy28;
					goto yy14;
				} else {
					if (yych == '|') goto yy29;
					goto yy4;
				}
			}
		}
	}
yy2:
	++p;
	{ token = TEOF;     break; }
yy4:
	++p;
yy5:
	{ token = ERROR;    break; }
yy6:
	++p;
	{ token = NEWLINE;  break; }
yy8:
	yych = *++p;
	if (yych == '\n') goto yy31;
	goto yy5;
yy9:
	yyaccept = 0;
	q = ++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy9;
	}
	if (yych <= '\f') {
		if (yych == '\n') goto yy6;
	} else {
		if (yych <= '\r') goto yy33;
		if (yych == '#') goto yy35;
	}
yy11:
	{ token = INDENT;   break; }
yy12:
	yyaccept = 1;
	yych = *(q = ++p);
	if (yych <= 0x00) goto yy5;
	goto yy36;
yy13:
	yych = *++p;
	if (yych == '=') goto yy39;
	goto yy5;
yy14:
	++p;
	yych = *p;
yy15:
	if (yybm[0+yych] & 64) {
		goto yy14;
	}
	{ token = IDENT;    break; }
yy17:
	++p;
	{ token = COLON;    break; }
yy19:
	++p;
	{ token = EQUALS;   break; }
yy21:
	yych = *++p;
	if (yych == 'u') goto yy41;
	goto yy15;
yy22:
	yych = *++p;
	if (yych == 'e') goto yy42;
	goto yy15;
yy23:
	yych = *++p;
	if (yych == 'n') goto yy43;
	goto yy15;
yy24:
	yych = *++p;
	if (yych == 'o') goto yy44;
	goto yy15;
yy25:
	yych = *++p;
	if (yych == 'n') goto yy45;
	goto yy15;
yy26:
	yych = *++p;
	if (yych == 'o') goto yy47;
	goto yy15;
yy27:
	yych = *++p;
	if (yych == 'u') goto yy48;
	goto yy15;
yy28:
	yych = *++p;
	if (yych == 'u') goto yy49;
	goto yy15;
yy29:
	++p;
	if ((yych = *p) == '|') goto yy50;
	{ token = PIPE;     break; }
yy31:
	++p;
	{ token = NEWLINE;  break; }
yy33:
	yych = *++p;
	if (yych == '\n') goto yy31;
yy34:
	p = q;
	if (yyaccept == 0) {
		goto yy11;
	} else {
		goto yy5;
	}
yy35:
	++p;
	yych = *p;
yy36:
	if (yybm[0+yych] & 128) {
		goto yy35;
	}
	if (yych <= 0x00) goto yy34;
	++p;
	{ continue; }
yy39:
	++p;
	{ token = PLUSEQ;   break; }
yy41:
	yych = *++p;
	if (yych == 'i') goto yy52;
	goto yy15;
yy42:
	yych = *++p;
	if (yych == 'f') goto yy53;
	goto yy15;
yy43:
	yych = *++p;
	if (yych == 'd') goto yy54;
	goto yy15;
yy44:
	yych = *++p;
	if (yych == 'r') goto yy56;
	goto yy15;
yy45:
	++p;
	if ((yych = *p) <= 'Z') {
		if (yych <= '/') {
			if (yych <= ',') goto yy46;
			if (yych <= '.') goto yy14;
		} else {
			if (yych <= '9') goto yy14;
			if (yych >= 'A') goto yy14;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy14;
		} else {
			if (yych == 'c') goto yy58;
			if (yych <= 'z') goto yy14;
		}
	}
yy46:
	{ token = IN_;      break; }
yy47:
	yych = *++p;
	if (yych == 'o') goto yy59;
	goto yy15;
yy48:
	yych = *++p;
	if (yych == 'l') goto yy60;
	goto yy15;
yy49:
	yych = *++p;
	if (yych == 'b') goto yy61;
	goto yy15;
yy50:
	++p;
	{ token = PIPE2;    break; }
yy52:
	yych = *++p;
	if (yych == 'l') goto yy62;
	goto yy15;
yy53:
	yych = *++p;
	if (yych == 'a') goto yy63;
	goto yy15;
yy54:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = END;      break; }
yy56:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = FOR;      break; }
yy58:
	yych = *++p;
	if (yych == 'l') goto yy64;
	goto yy15;
yy59:
	yych = *++p;
	if (yych == 'l') goto yy65;
	goto yy15;
yy60:
	yych = *++p;
	if (yych == 'e') goto yy67;
	goto yy15;
yy61:
	yych = *++p;
	if (yych == 'n') goto yy69;
	goto yy15;
yy62:
	yych = *++p;
	if (yych == 'd') goto yy70;
	goto yy15;
yy63:
	yych = *++p;
	if (yych == 'u') goto yy72;
	goto yy15;
yy64:
	yych = *++p;
	if (yych == 'u') goto yy73;
	goto yy15;
yy65:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = POOL;     break; }
yy67:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = RULE;     break; }
yy69:
	yych = *++p;
	if (yych == 'i') goto yy74;
	goto yy15;
yy70:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = BUILD;    break; }
yy72:
	yych = *++p;
	if (yych == 'l') goto yy75;
	goto yy15;
yy73:
	yych = *++p;
	if (yych == 'd') goto yy76;
	goto yy15;
yy74:
	yych = *++p;
	if (yych == 'n') goto yy77;
	goto yy15;
yy75:
	yych = *++p;
	if (yych == 't') goto yy78;
	goto yy15;
yy76:
	yych = *++p;
	if (yych == 'e') goto yy80;
	goto yy15;
yy77:
	yych = *++p;
	if (yych == 'j') goto yy82;
	goto yy15;
yy78:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = DEFAULT;  break; }
yy80:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = INCLUDE;  break; }
yy82:
	yych = *++p;
	if (yych != 'a') goto yy15;
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy14;
	}
	{ token = SUBNINJA; break; }
}

  }

  last_token_ = start;
  ofs_ = p;
  if (token != NEWLINE && token != TEOF)
    EatWhitespace();
  return token;
}

bool Lexer::PeekToken(Token token) {
  Token t = ReadToken();
  if (t == token)
    return true;
  UnreadToken();
  return false;
}

void Lexer::EatWhitespace() {
  const char* p = ofs_;
  const char* q;
  for (;;) {
    ofs_ = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy91;
	}
	if (yych <= 0x00) goto yy87;
	if (yych == '$') goto yy94;
	goto yy89;
yy87:
	++p;
	{ break; }
yy89:
	++p;
yy90:
	{ break; }
yy91:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy91;
	}
	{ continue; }
yy94:
	yych = *(q = ++p);
	if (yych == '\n') goto yy95;
	if (yych == '\r') goto yy97;
	goto yy90;
yy95:
	++p;
	{ continue; }
yy97:
	yych = *++p;
	if (yych == '\n') goto yy99;
	p = q;
	goto yy90;
yy99:
	++p;
	{ continue; }
}

  }
}

bool Lexer::ReadIdent(string* out) {
  const char* p = ofs_;
  for (;;) {
    const char* start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0, 128, 128,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy105;
	}
	++p;
	{ return false; }
yy105:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy105;
	}
	{
      out->assign(start, p - start);
      break;
    }
}

  }
  ofs_ = p;
  EatWhitespace();
  return true;
}

bool Lexer::ReadEvalString(EvalString* eval, string *special2, bool path, string* err) {
  const char* p = ofs_;
  const char* q;
  const char* start;
  if (special2)
	  *special2="";
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,   0,  16,  16,   0,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 32,  16,  16,  16,   0,  16,  16,  16, 
		 16,  16,  16,  16,  16, 208, 144,  16, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208,   0,  16,  16,  16,  16,  16, 
		 16, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208,  16,  16,  16,  16, 208, 
		 16, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208,  16,   0,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
	};
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy112;
	}
	if (yych <= '\r') {
		if (yych <= 0x00) goto yy110;
		if (yych <= '\n') goto yy115;
		goto yy117;
	} else {
		if (yych <= ' ') goto yy115;
		if (yych <= '$') goto yy119;
		goto yy115;
	}
yy110:
	++p;
	{
      last_token_ = start;
      return Error("unexpected EOF", err);
    }
yy112:
	++p;
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy112;
	}
	{
      eval->AddText(StringPiece(start, p - start));
      continue;
    }
yy115:
	++p;
	{
      if (path) {
        p = start;
        break;
      } else {
        if (*start == '\n')
          break;
        eval->AddText(StringPiece(start, 1));
        continue;
      }
    }
yy117:
	++p;
	if ((yych = *p) == '\n') goto yy120;
	{
      last_token_ = start;
      return Error(DescribeLastError(), err);
    }
yy119:
	yych = *++p;
	if (yybm[0+yych] & 64) {
		goto yy133;
	}
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy124;
			goto yy122;
		} else {
			if (yych <= '\r') goto yy127;
			if (yych == ' ') goto yy128;
			goto yy122;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy130;
			if (yych == '(') goto yy132;
			goto yy122;
		} else {
			if (yych <= ':') goto yy136;
			if (yych <= '`') goto yy122;
			if (yych <= '{') goto yy138;
			goto yy122;
		}
	}
yy120:
	++p;
	{
      if (path)
        p = start;
      break;
    }
yy122:
	++p;
yy123:
	{
      last_token_ = start;
      return Error("bad $-escape (literal $ must be written as $$)", err);
    }
yy124:
	++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy124;
	}
	{
      continue;
    }
yy127:
	yych = *++p;
	if (yych == '\n') goto yy139;
	goto yy123;
yy128:
	++p;
	{
      eval->AddText(StringPiece(" ", 1));
      continue;
    }
yy130:
	++p;
	{
      eval->AddText(StringPiece("$", 1));
      continue;
    }
yy132:
	yych = *(q = ++p);
	if (yybm[0+yych] & 128) {
		goto yy142;
	}
	goto yy123;
yy133:
	++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy133;
	}
	{
      eval->AddSpecial(StringPiece(start + 1, p - start - 1));
      continue;
    }
yy136:
	++p;
	{
      eval->AddText(StringPiece(":", 1));
      continue;
    }
yy138:
	yych = *(q = ++p);
	if (yych <= '@') {
		if (yych <= '.') {
			if (yych <= ',') goto yy123;
			goto yy145;
		} else {
			if (yych <= '/') goto yy123;
			if (yych <= '9') goto yy145;
			goto yy123;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy145;
			if (yych <= '^') goto yy123;
			goto yy145;
		} else {
			if (yych <= '`') goto yy123;
			if (yych <= 'z') goto yy145;
			goto yy123;
		}
	}
yy139:
	++p;
	yych = *p;
	if (yych == ' ') goto yy139;
	{
      continue;
    }
yy142:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy142;
	}
	if (yych == ')') goto yy147;
yy144:
	p = q;
	goto yy123;
yy145:
	++p;
	yych = *p;
	if (yych <= 'Z') {
		if (yych <= '/') {
			if (yych <= ',') goto yy144;
			if (yych <= '.') goto yy145;
			goto yy144;
		} else {
			if (yych <= '9') goto yy145;
			if (yych <= '@') goto yy144;
			goto yy145;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy145;
			goto yy144;
		} else {
			if (yych <= 'z') goto yy145;
			if (yych == '}') goto yy149;
			goto yy144;
		}
	}
yy147:
	++p;
	{
      if (!special2)
        return Error("recursive $(variable) expansion", err);
      *special2=StringPiece(start + 2, p - start - 3).AsString();
      break;
    }
yy149:
	++p;
	{
      eval->AddSpecial(StringPiece(start + 2, p - start - 3));
      continue;
    }
}

  }
  last_token_ = start;
  ofs_ = p;
  if (path)
    EatWhitespace();
  // Non-path strings end in newlines, so there's no whitespace to eat.
  return true;
}
